var PRESETS ={}

const RAREPEPES = [
    "BACHELORPEPE",
    "BACKPAGEPEPE",
    "BACKTOPEPE",
    "BADASSPEPE",
    "BADHAIRDAY",
    "BADLTPEPE",
    "BAGHOLDRPEPE",
    "BANANAPEPE",
    "BANDAGEDPEPE",
    "BANEPEPE",
    "BANKRUPTPEPE",
    "BAPEPE",
    "BARBARICPEPE",
    "BARRYPEPE",
    "BATBUTBOO",
    "BATMANPEPE",
    "BATTLEPEPE",
    "BAYLOP",
    "BBAEPEPE",
    "BBOYPEPE",
    "BEACHPEPE",
    "BEATLESPEPE",
    "BEATPEPE",
    "BEETLEPEPE",
    "BEHAPPYPEPE",
    "BENDERPEPE",
    "BERLINPEPE",
    "BERNIEPEPE",
    "BETTYPEPE",
    "BEWPEPE",
    "BIGGIEPEPE",
    "BIGVERNPEPE",
    "BILLNTEDPEPE",
    "BINARYPEPE",
    "BITCOINPEPE",
    "BITGIRLPEPE",
    "BLAINEPEPE",
    "BLINGBLING",
    "BLKCHNJESUS",
    "BLKSWANPEPE",
    "BLOCKPEPE",
    "BLOWPEPE",
    "BOBDOBBS",
    "BOFPEPE",
    "BOGDAPEPE",
    "BOMINABLPEPE",
    "BONDPEPE",
    "BOSSHOGPEPE",
    "BOWIEPEP",
    "BOWLPEPE",
    "BOYSCLUBPEPE",
    "BOYZIIPEPE",
    "BREATHEDPEPE",
    "BRIGHTONPEPE",
    "BTCPEPE",
    "BTFDPEPE",
    "BTTLFTHESUBS",
    "BUBREAKUP",
    "BUDDHAPEPES",
    "BUGSPEPE",
    "BULBAPEPECRD",
    "BULLYPEPE",
    "BUPEPE",
    "BURNINGPEPE",
    "BURNPEPE",
    "CALLHOTPEPE",
    "CANNEDPEPE",
    "CANNONPEPE",
    "CANTDRAWPEPE",
    "CARCRASHPEPE",
    "CARTOONPEPE",
    "CEETHREEPEPE",
    "CHAMPAGNETNT",
    "CHEECHPEPE",
    "CHERPEPEFOIL",
    "CHIKUNPEPE",
    "CHINAPEPE",
    "CHOCOPEPE",
    "CHONGPEPE",
    "CHUNRIPEPE",
    "CHYNAPEPE",
    "CICACOINPEPE",
    "CINDERPEPE",
    "CINEKEK",
    "CIRCLEOFPEPE",
    "CLASSICPEPE",
    "CLAYPEPE",
    "CLCKWRKGREEN",
    "CLIFFORDPEPE",
    "CLOWNPEPE",
    "CLUBPEPE",
    "CMNWRKRPEPE",
    "CNPEPE",
    "CNTRFLDPEPE",
    "COLDPEPE",
    "COLORPEPE",
    "COMEDYPEPE",
    "CONFUSEDPEPE",
    "COVPEPERARE",
    "CPTMRICAPEPE",
    "CREMAPEPE",
    "CREWLOVEPEPE",
    "CROPPEPE",
    "CRUSADERPEPE",
    "CRYPTOPEPE",
    "CRYSTALPEPE",
    "CSAT",
    "CUBANPEPE",
    "CUBEPEPE",
    "CUBISTPEPE",
    "CULTOFKEK",
    "CULTOFPEPE",
    "CUPIDPEPE",
    "CYBERPEPE",
    "DABPEPE",
    "DALIPEPE",
    "DANKPEPE",
    "DANKVADER",
    "DANNIBOIPEPE",
    "DANPEPERIAN",
    "DAOPEPEHACK",
    "DAPHNIAPEPE",
    "DAPPERPEPE",
    "DARKPILLPEPE",
    "DARKSIDEPEPE",
    "DASHPEPE",
    "DATPEPE",
    "DDDPEPE",
    "DEBATEPEPE",
    "DECENTRAPEPE",
    "DEEPWEBPEPE",
    "DEEZPEPENUTS",
    "DEGENERPEPE",
    "DELOREANPEPE",
    "DEUSEXPEPE",
    "DEXTERPEPE",
    "DIAVOLO",
    "DIERCHANCHU",
    "DJPEPE",
    "DOCTORPEPE",
    "DOGEVSPEPE",
    "DOGGYPUTIN",
    "DOGSALL",
    "DOHCASH",
    "DOKUGANPEPE",
    "DOLLARPEPE",
    "DOMPEPENON",
    "DONTBEMENACE",
    "DORAETROLL",
    "DOSPEPES",
    "DOTPEPE",
    "DOUBLEPEPE",
    "DRAGONKEK",
    "DRATHPEPE",
    "DRDIRTYPEPE",
    "DRILLPEPE",
    "DRONEPEPE",
    "DROPPEPE",
    "DRSTRNGEPEPE",
    "DRUNKENPEPE",
    "DUMBLEPEPE",
    "DUMMIES",
    "EARTHPEPE",
    "EAZYP",
    "ECCEPEPE",
    "EGGPLANTPEPE",
    "EINSTEINPEPE",
    "ELEVATORPEPE",
    "EMBRYOPEPE",
    "EMPERORPEPE",
    "ENDRACISMPE",
    "ENGELPEPE",
    "ENGLISHPEPE",
    "ENTERTHEPEPE",
    "EPEENPEPE",
    "EPEPESODEONE",
    "ERDOPEPEGAN",
    "ERISPEPE",
    "ETHERPEPE",
    "EXCLUPEPE",
    "EXKEKUTIONER",
    "EYEOFTHEPEPE",
    "EYETESTPEPE",
    "FAIRPEPE",
    "FAIRYODDPEPE",
    "FAKERPEPE",
    "FASTPEPE",
    "FATHERPEPE",
    "FATPEPE",
    "FATPEPSLIM",
    "FEATHERSPEPE",
    "FEELSGOODMAN",
    "FEELSPEPE",
    "FIGHTPEPE",
    "FIGHTSYSTEM",
    "FILEONPEPE",
    "FINNPEPE",
    "FINNTHEPEPE",
    "FIREASSPEPE",
    "FISHERPEPE",
    "FLAPPYPEPE",
    "FLATEARTH",
    "FLINTPEPE",
    "FLOWERPEPE",
    "FLUFFYPEPES",
    "FLYINGACEPEP",
    "FOLDERPEPE",
    "FORBIDENPEPE",
    "FORTYTWOPEPE",
    "FRACTALPEPE",
    "FRATPEPE",
    "FREEMYPEPE",
    "FREETIBETPP",
    "FRENCHPEPE",
    "FRESHPEPE",
    "FRIENDSPEPE",
    "FROGBUS",
    "FRYPEPE",
    "FSBPUTINPEPE",
    "FSMPEPE",
    "FTERTHERAIN",
    "FUJINPEPE",
    "FULLMETALPEP",
    "FULMETALPEPE",
    "FUNPEPE",
    "FUTURESPEPE",
    "GADGETPEPE",
    "GADSDENPEPE",
    "GAINSPEPE",
    "GAIUSPEPEUS",
    "GAMEBOIPEPE",
    "GAMEOFPEPE",
    "GAMESOFTRUMP",
    "GANGPEPE",
    "GAUDISPEPE",
    "GEISHAPEPE",
    "GENIEPEPE",
    "GETPEPEFREE",
    "GIPEPE",
    "GIVEKUDOS",
    "GLDPEPE",
    "GLUTTONYPEPE",
    "GNITEPEPE",
    "GNUPEPE",
    "GODALIEN",
    "GODAMUNRA",
    "GODANUBIS",
    "GODDESSHEQET",
    "GODDESSISIS",
    "GODEMPEPE",
    "GOKUPEPE",
    "GOLDGODPEPE",
    "GOODBYEPEPE",
    "GOODNITEPEPE",
    "GOSPELPEPE",
    "GOTHICPEPE",
    "GOTPEPESHIRT",
    "GOXPEPE",
    "GRAFFITIPEPE",
    "GRANDPEPE",
    "GRANDPEPES",
    "GREEDYPEPES",
    "GRIMPEPE",
    "GRNDMSTRPEPE",
    "GTAPEP",
    "GTPEPE",
    "GUARDSASKIAN",
    "GUARDSPEPE",
    "GUESSWHATPEP",
    "GUMMYPEPE",
    "GURUPEPE",
    "GUYBRUSH",
    "HAIKUPEPE",
    "HAIRPEPE",
    "HANGINPEPE",
    "HANNIBALPEPE",
    "HANPEPE",
    "HANSEIPEPE",
    "HAPPYRAINY",
    "HARAMPEPE",
    "HARDPEPEFORK",
    "HARRYPEPES",
    "HEISENPEPE",
    "HEKET",
    "HELOPEPE",
    "HERNIAPEPE",
    "HICKSPEPE",
    "HILLARYPEPE",
    "HIPPIEPEPE",
    "HISTORICPEPE",
    "HLYPEPANCAKE",
    "HODLWOOD",
    "HOLYPEPE",
    "HOMERPEPE",
    "HORRORPEPE",
    "HOTLINEPEPE",
    "HULAPEPE",
    "HULKPEPE",
    "HUMBLEPEPE",
    "HWNDUPEPE",
    "HYIPPEPE",
    "HYPNOPEPE",
    "HYPNOTIST",
    "ICARUSPEPE",
    "ICPEPE",
    "ICQPEPE",
    "ILLIDANPEPE",
    "ILLUMINATIPE",
    "ILOVEPEPE",
    "IMWITHPEPE",
    "INCREDIEPEPE",
    "INNOCOINBOT",
    "INVISIBLPEPE",
    "IRONMANPEPE",
    "IRONPEPE",
    "ISEEYOUPEPE",
    "ISOPEPE",
    "IWANTTOPEPE",
    "JACKOPEPE",
    "JACKPOTPEPE",
    "JAKETHEPEPE",
    "JALAPEPE",
    "JAPANESEPEPE",
    "JASMINEPEPE",
    "JESUSPEPE",
    "JIHANWU",
    "JINQIANSHU",
    "JJPEPE",
    "JMPEPEKEYNES",
    "JOELOONEYBIN",
    "JOINTPEPE",
    "JOJOXPEPE",
    "JOKERPE",
    "JOKERPEPEKEK",
    "JONGPEPE",
    "JONSNOWPEPE",
    "JPEPE",
    "JSSICAPEPE",
    "JUNSETHPEPE",
    "JUSTINTPEPE",
    "JWPEPE",
    "KABUKIPEPE",
    "KAMIKAZEPEPE",
    "KANDINSKYPEP",
    "KAPPAPEPE",
    "KARTANDPEPE",
    "KATYPEPE",
    "KAWAPEPE",
    "KEISERPEPE",
    "KEKALITY",
    "KEKANC",
    "KEKENESIS",
    "KEKET",
    "KEKISTAN",
    "KEKLORDGABEN",
    "KEKOFWAR",
    "KEKPEPE",
    "KEKRELOADED",
    "KEKRESURRECT",
    "KEKSBASILISK",
    "KEKTOPUS",
    "KEKUI",
    "KEKUIT",
    "KEKVSMOLOCH",
    "KEKWAVE",
    "KEROPEPE",
    "KEYBOARDPEPE",
    "KICKPEPE",
    "KIDPEPE",
    "KIGURUMIPEPE",
    "KILLARYPEPE",
    "KINGYOPEPE",
    "KITANO",
    "KKPEPE",
    "KNITTEDPEPE",
    "KOIPEPE",
    "KOJIPEPE",
    "KPEPE",
    "KUMADORIPEPE",
    "KUNGFUPEPE",
    "KUNISADAPEPE",
    "LAUTRECPEPE",
    "LEANPEPE",
    "LEDZEPEPELIN",
    "LEGENDOFPEPE",
    "LEGOPEPE",
    "LEIAPEPE",
    "LEOPEPESCAM",
    "LEPEWPEPE",
    "LETSTALKKEK",
    "LEVELUPPEPE",
    "LIAMPEPE",
    "LIBERPEPE",
    "LIBERTYPEPE",
    "LIKEPEPEBRO",
    "LILMERMAID",
    "LILUPEPE",
    "LISKPPAPPEPE",
    "LITTLEBOPEPE",
    "LIZZFACEPEPE",
    "LONELYPEPE",
    "LONGNOSEPEPE",
    "LORDGLEN",
    "LORDKEK",
    "LORDOFMEMES",
    "LORDSHIVA",
    "LOVEISPEPE",
    "LOVEPEPETATO",
    "LOWRIDERPEPE",
    "LUCHAPEPE",
    "LUCKYPEPE",
    "LUKEJRPEPE",
    "LUPEPEN",
    "MADARAPEPE",
    "MADMAXPEPE",
    "MAGICPEPEYE",
    "MAKEPEPERARE",
    "MANDARAPEPE",
    "MANDELPEPE",
    "MAOISMPEPE",
    "MAOPEPE",
    "MAOZEPEPE",
    "MAPEPENEMR",
    "MARIACHIPEPE",
    "MARINEPEINE",
    "MARSPEPE",
    "MARTYPEPFLY",
    "MARVINPEPE",
    "MASTEROFPEPE",
    "MASTERSPEPE",
    "MASTROPEPE",
    "MATADORPEPE",
    "MATISSEPEPE",
    "MATSUNIPEPE",
    "MATSURIPEPE",
    "MAUIPEPE",
    "MAXPEPE",
    "MAYWEATHPEPE",
    "MCGREGOR",
    "MCPEPE",
    "MCPEPEDEBUFF",
    "MCPEPESCHER",
    "MEDICINEPEPE",
    "MELANCHOLIA",
    "MELANCOLIE",
    "MEMEFIGHTERS",
    "MEMESTEALER",
    "MEMETICMAGIC",
    "MEMPOOLPEPE",
    "MERKLETREEPE",
    "MFPEPE",
    "MIDIPEPE",
    "MIKOPEPE",
    "MINDPEPEHOFF",
    "MINIONPEPE",
    "MIRACLEPEPE",
    "MIROPEPE",
    "MISSPEPE",
    "MISSTURNPEPE",
    "MIYAKO",
    "MNTNDWRVSMNG",
    "MOAIPEPE",
    "MOBBPEPE",
    "MOBIUSPEPE",
    "MODERNPEPE",
    "MODIPEPE",
    "MONALISAPEPE",
    "MONBOURARNO",
    "MONEYPEPE",
    "MONOPEPEOLY",
    "MONSTERPEPE",
    "MONTYPEPE",
    "MOONPEPE",
    "MOONWAVEPEPE",
    "MORNINGPEPE",
    "MORPHEUSPEPE",
    "MRHANSEL",
    "MRPOTATOPEPE",
    "MRPPBUTTHOLE",
    "MRSTAYPEPT",
    "MTPEPEMORE",
    "MUNETOPEPE",
    "MURICAPEPE",
    "MYFIRSTPEPE",
    "MYLADYPEPE",
    "MYLITTLEPEPE",
    "MYPEPELITTLE",
    "MYRIADMPEPE",
    "MYSPEPE",
    "MYSTERYPEPE",
    "NAHUAL",
    "NAMIDAPEPE",
    "NAPALMPEPE",
    "NAPKINPEPE",
    "NASPEPE",
    "NATIVEPEPETH",
    "NECROPEPE",
    "NEEDPEPE",
    "NEONFROGS",
    "NEONPEPE",
    "NEOPEPE",
    "NEUROPEPE",
    "NEWYEARPEPE",
    "NICOLAPEPE",
    "NICOSARKOS",
    "NIGHTSATPEPE",
    "NINEFIVEPEPA",
    "NINJAPEPE",
    "NINJAPEPES",
    "NMPPEPE",
    "NOBORDERPEPE",
    "NOBRAKESPEPE",
    "NOFAPPEPE",
    "NOFUCKSPUTIN",
    "NOHPEPE",
    "NULLCPEPE",
    "NURSEPEPE",
    "NYANPEPE",
    "OBEYPEPE",
    "OLYMPICPEPE",
    "ONEPUNCHPEPE",
    "ONLYONEPEPE",
    "OPPPEPE",
    "OPTIMUSPEPE",
    "ORTRAILPEPE",
    "OSKARPEPE",
    "OWLPEPE",
    "PACPEP",
    "PACPEPE",
    "PAKALOLO",
    "PAPILLON",
    "PARTYPEPE",
    "PAWNTHELAMBO",
    "PBOCPEPE",
    "PEAKYPEPE",
    "PEEKABOOPEPE",
    "PEEPHOLEPEPE",
    "PEKMAN",
    "PENIC",
    "PENPEN",
    "PEPA",
    "PEPAPINUP",
    "PEPEA",
    "PEPEAA",
    "PEPEACE",
    "PEPEACIDTRIP",
    "PEPEADDAMS",
    "PEPEADDICT",
    "PEPEAFRIKA",
    "PEPEAGYO",
    "PEPEAIR",
    "PEPEAIRLINES",
    "PEPEAKI",
    "PEPEALASSAD",
    "PEPEALIEN",
    "PEPEAMANDA",
    "PEPEAMAZING",
    "PEPEAMCANI",
    "PEPEAMD",
    "PEPEAN",
    "PEPEANDFEELS",
    "PEPEANDROID",
    "PEPEANDSON",
    "PEPEANDY",
    "PEPEANGRY",
    "PEPEANON",
    "PEPEARCHER",
    "PEPEARROW",
    "PEPEART",
    "PEPEARTHUR",
    "PEPEARTISTE",
    "PEPEASSANGE",
    "PEPEASTRO",
    "PEPEASTROBOY",
    "PEPEASTRONAT",
    "PEPEASYSQUEZ",
    "PEPEATARI",
    "PEPEAUCTIOND",
    "PEPEAUDIOPHL",
    "PEPEAXEGANG",
    "PEPEBACKPACK",
    "PEPEBALL",
    "PEPEBALT",
    "PEPEBANDICUT",
    "PEPEBANG",
    "PEPEBASQUIAT",
    "PEPEBASS",
    "PEPEBEARD",
    "PEPEBEARWHLE",
    "PEPEBEEFTAXI",
    "PEPEBERLUSCA",
    "PEPEBGDWORK",
    "PEPEBILL",
    "PEPEBIRTH",
    "PEPEBOBBY",
    "PEPEBONGSPHP",
    "PEPEBOUNTY",
    "PEPEBOW",
    "PEPEBOY",
    "PEPEBRAIN",
    "PEPEBRANDO",
    "PEPEBRARIAN",
    "PEPEBREAKUP",
    "PEPEBREEDER",
    "PEPEBRELLA",
    "PEPEBRICCO",
    "PEPEBRICK",
    "PEPEBRICKJR",
    "PEPEBRIEFS",
    "PEPEBROKEBU",
    "PEPEBROOM",
    "PEPEBROS",
    "PEPEBUCKET",
    "PEPEBUCKS",
    "PEPEBUGGED",
    "PEPEBURGUNDY",
    "PEPEBURN",
    "PEPEBURNED",
    "PEPEBUSTER",
    "PEPEBUSYFLOR",
    "PEPECAKEFACE",
    "PEPECAMERA",
    "PEPECAMO",
    "PEPECANCAN",
    "PEPECAPCHA",
    "PEPECARNIVAL",
    "PEPECASH",
    "PEPECASTRO",
    "PEPECCOLO",
    "PEPECENT",
    "PEPECGYVER",
    "PEPECHAININ",
    "PEPECHAIRMAN",
    "PEPECHARLES",
    "PEPECHE",
    "PEPECHPLGHTR",
    "PEPECIGARS",
    "PEPECINDERS",
    "PEPECITY",
    "PEPECLOKWORK",
    "PEPECLUB",
    "PEPECOASTER",
    "PEPECOLLECT",
    "PEPECONCERT",
    "PEPECONDOM",
    "PEPECONF",
    "PEPECONTRACT",
    "PEPECOUNTER",
    "PEPECOURAGE",
    "PEPECOWBELL",
    "PEPECREAM",
    "PEPECRYSTAL",
    "PEPEDABOMB",
    "PEPEDANCE",
    "PEPEDARK",
    "PEPEDARKSIDE",
    "PEPEDATA",
    "PEPEDAVID",
    "PEPEDDIT",
    "PEPEDEALWTHT",
    "PEPEDETCTVE",
    "PEPEDEX",
    "PEPEDHARMA",
    "PEPEDIEPIE",
    "PEPEDIRECTOR",
    "PEPEDJ",
    "PEPEDOL",
    "PEPEDON",
    "PEPEDOTCOM",
    "PEPEDOTS",
    "PEPEDRACULA",
    "PEPEDRAGO",
    "PEPEDRAKE",
    "PEPEDROID",
    "PEPEDRYAD",
    "PEPEDUCK",
    "PEPEDUCREUX",
    "PEPEDUROV",
    "PEPEDWARD",
    "PEPEDZILLA",
    "PEPEENEUMAN",
    "PEPEEVO",
    "PEPEFALLOUT",
    "PEPEFAMOUS",
    "PEPEFATHER",
    "PEPEFAUCET",
    "PEPEFETT",
    "PEPEFICRIM",
    "PEPEFIFTYONE",
    "PEPEFLATION",
    "PEPEFLECTION",
    "PEPEFLESH",
    "PEPEFLORIST",
    "PEPEFMYLIFE",
    "PEPEFOBIA",
    "PEPEFOCUSED",
    "PEPEFONDLERS",
    "PEPEFOREVER",
    "PEPEFORM",
    "PEPEFRACTAL",
    "PEPEFRED",
    "PEPEFREEDOM",
    "PEPEFREEZE",
    "PEPEFRENCH",
    "PEPEFREQ",
    "PEPEFROMHELL",
    "PEPEFUDUP",
    "PEPEFUYU",
    "PEPEGAIA",
    "PEPEGAMBIT",
    "PEPEGANDHI",
    "PEPEGAPHONE",
    "PEPEGATES",
    "PEPEGETABLE",
    "PEPEGHIDORAH",
    "PEPEGIGA",
    "PEPEGIGGITY",
    "PEPEGIRL",
    "PEPEGLOBE",
    "PEPEGLOVER",
    "PEPEGOAT",
    "PEPEGODDESS",
    "PEPEGOKU",
    "PEPEGOLDBAR",
    "PEPEGOLDRUSH",
    "PEPEGOLUM",
    "PEPEGOODY",
    "PEPEGOP",
    "PEPEGOTCHI",
    "PEPEGOTSICK",
    "PEPEGOTSWAG",
    "PEPEGOTTIME",
    "PEPEGRAM",
    "PEPEGRAVE",
    "PEPEGREEN",
    "PEPEGROOT",
    "PEPEGROUNDS",
    "PEPEGUEVARA",
    "PEPEGUITAR",
    "PEPEGUN",
    "PEPEHAMMER",
    "PEPEHAND",
    "PEPEHARDTALK",
    "PEPEHARING",
    "PEPEHARU",
    "PEPEHEFNER",
    "PEPEHELP",
    "PEPEHELTEACH",
    "PEPEHEMAN",
    "PEPEHEPBURN",
    "PEPEHERO",
    "PEPEHEXCHANT",
    "PEPEHIGHTOWR",
    "PEPEHITMAN",
    "PEPEHODLER",
    "PEPEHOFFMAN",
    "PEPEHOLOGRAM",
    "PEPEHOMER",
    "PEPEHONDO",
    "PEPEHOPE",
    "PEPEHORROR",
    "PEPEHOTEP",
    "PEPEHOUSE",
    "PEPEHUANA",
    "PEPEHUNGRY",
    "PEPEHUNTER",
    "PEPEICHIGO",
    "PEPEILLUSION",
    "PEPEIMPOSER",
    "PEPEIMPOSTOR",
    "PEPEINSHADES",
    "PEPEINSIDE",
    "PEPEINTRO",
    "PEPEIRI",
    "PEPEIRON",
    "PEPEISLOVE",
    "PEPEISNUBLK",
    "PEPEISOTTO",
    "PEPEISPEACE",
    "PEPEISUNITY",
    "PEPEJAPAN",
    "PEPEJEANS",
    "PEPEJERICHO",
    "PEPEJIRAIYA",
    "PEPEJIRO",
    "PEPEJOANARC",
    "PEPEJOBS",
    "PEPEJOHNS",
    "PEPEJOINTSPH",
    "PEPEJOKER",
    "PEPEJONES",
    "PEPEJORN",
    "PEPEJOSE",
    "PEPEJPN",
    "PEPEJUDGE",
    "PEPEJUGGLER",
    "PEPEJUICE",
    "PEPEKACHU",
    "PEPEKAPARKER",
    "PEPEKARLMARX",
    "PEPEKARMA",
    "PEPEKART",
    "PEPEKEEPER",
    "PEPEKEK",
    "PEPEKEKCOIN",
    "PEPEKEN",
    "PEPEKICKS",
    "PEPEKIDROBOT",
    "PEPEKIDSART",
    "PEPEKIM",
    "PEPEKMONGO",
    "PEPEKNIEVEL",
    "PEPEKONGBIGM",
    "PEPEKYRIE",
    "PEPELAMA",
    "PEPELAMBO",
    "PEPELAND",
    "PEPELANDER",
    "PEPELARGE",
    "PEPELAVEY",
    "PEPELCHTNSTN",
    "PEPELEFTLEG",
    "PEPELEGOMAN",
    "PEPELEMMING",
    "PEPELENNON",
    "PEPELEO",
    "PEPELEPEW",
    "PEPELETTERA",
    "PEPELEVI",
    "PEPELEVICH",
    "PEPELEWINSKY",
    "PEPELIBRARY",
    "PEPELIKE",
    "PEPELINK",
    "PEPELITTLE",
    "PEPELLUM",
    "PEPELMINING",
    "PEPELOOP",
    "PEPELOU",
    "PEPELOUX",
    "PEPELSD",
    "PEPELUFFY",
    "PEPELVSD",
    "PEPELYN",
    "PEPELYNMASON",
    "PEPEMACARONI",
    "PEPEMANE",
    "PEPEMANTIS",
    "PEPEMAONE",
    "PEPEMAORI",
    "PEPEMARAUDER",
    "PEPEMARIOLR",
    "PEPEMARKET",
    "PEPEMARLEY",
    "PEPEMAXAF",
    "PEPEMCLOVIN",
    "PEPEME",
    "PEPEMEETUPBK",
    "PEPEMEGAMAN",
    "PEPEMEMECARD",
    "PEPEMILEY",
    "PEPEMILLION",
    "PEPEMINING",
    "PEPEMINO",
    "PEPEMINT",
    "PEPEMIRROR",
    "PEPEMOM",
    "PEPEMOMWRATH",
    "PEPEMONROE",
    "PEPEMONTOYA",
    "PEPEMOON",
    "PEPEMORPHS",
    "PEPEMOTHRA",
    "PEPEMOVIE",
    "PEPEMPTYWLLT",
    "PEPENACCI",
    "PEPENAL",
    "PEPENAPOLEON",
    "PEPENARUTO",
    "PEPENATION",
    "PEPENATTI",
    "PEPENCEPTION",
    "PEPENEWTON",
    "PEPENGAROO",
    "PEPENGHTMUM",
    "PEPENIETZSCH",
    "PEPENIKOLAI",
    "PEPENIN",
    "PEPENITOR",
    "PEPENOFF",
    "PEPENOMIST",
    "PEPENOPOULOS",
    "PEPENORMIES",
    "PEPENORRIS",
    "PEPENOSAURUS",
    "PEPENSTEIN",
    "PEPENUKES",
    "PEPENUMA",
    "PEPENUT",
    "PEPEOFTHEUSA",
    "PEPEOLDCASH",
    "PEPEOLDCHAP",
    "PEPEOLDTRADE",
    "PEPEOMUERTE",
    "PEPEON",
    "PEPEONE",
    "PEPEONECOIN",
    "PEPEONMUSK",
    "PEPEORACLE",
    "PEPEOROCHI",
    "PEPEOTHERARM",
    "PEPEOTHERLEG",
    "PEPEOUTSIDE",
    "PEPEPALACE",
    "PEPEPAMPERS",
    "PEPEPARADISE",
    "PEPEPARADO",
    "PEPEPARTY",
    "PEPEPASSPORT",
    "PEPEPAWNSHOP",
    "PEPEPEACE",
    "PEPEPEANUTS",
    "PEPEPEARL",
    "PEPEPENPEN",
    "PEPEPET",
    "PEPEPHARAON",
    "PEPEPHONEHOM",
    "PEPEPILLOW",
    "PEPEPIRATE",
    "PEPEPIZZA",
    "PEPEPLISSKEN",
    "PEPEPOET",
    "PEPEPOLLOCK",
    "PEPEPONY",
    "PEPEPOOL",
    "PEPEPOOR",
    "PEPEPOPE",
    "PEPEPORTRAIT",
    "PEPEPOWERONE",
    "PEPEPOWERTWO",
    "PEPEPRINGLES",
    "PEPEPSI",
    "PEPEPUFF",
    "PEPEPUMPETTE",
    "PEPEPUNCHOUT",
    "PEPEPUNKDOLL",
    "PEPEPYRAMID",
    "PEPERACCOON",
    "PEPERAGEQUIT",
    "PEPERAILWAYS",
    "PEPERAKUL",
    "PEPERAMBO",
    "PEPERANGER",
    "PEPERARE",
    "PEPERATATATT",
    "PEPERAZZIS",
    "PEPERBOY",
    "PEPEREALM",
    "PEPERECALL",
    "PEPERECHAUN",
    "PEPEREPUBLIC",
    "PEPEREQUEST",
    "PEPERETRO",
    "PEPERFUME",
    "PEPERGRIFFIN",
    "PEPERICH",
    "PEPERIDER",
    "PEPERIGHTARM",
    "PEPERIKISHI",
    "PEPERIVETER",
    "PEPERMAID",
    "PEPERMIND",
    "PEPEROGAN",
    "PEPERONCINO",
    "PEPEROSS",
    "PEPEROYAL",
    "PEPERREVENGE",
    "PEPERRIDA",
    "PEPERRR",
    "PEPERSEXUAL",
    "PEPERSSNRLTT",
    "PEPERUS",
    "PEPERUSSIAN",
    "PEPESACE",
    "PEPESAILOR",
    "PEPESAILORV",
    "PEPESAIYAN",
    "PEPESAKURA",
    "PEPESAMSON",
    "PEPESAX",
    "PEPESCAVHUNT",
    "PEPESCHEME",
    "PEPESCIENCE",
    "PEPESCOOBY",
    "PEPESCREAM",
    "PEPESCUBA",
    "PEPESEARCH",
    "PEPESHADES",
    "PEPESHELDON",
    "PEPESHIELD",
    "PEPESHIRT",
    "PEPESHKRELI",
    "PEPESHROOMS",
    "PEPESIGNGUY",
    "PEPESINCITY",
    "PEPESITO",
    "PEPESKATES",
    "PEPESKELETON",
    "PEPESMALLS",
    "PEPESMURF",
    "PEPESOUP",
    "PEPESOURCE",
    "PEPESPACE",
    "PEPESPIDER",
    "PEPESPINNER",
    "PEPESPLANET",
    "PEPESPRAY",
    "PEPESQRPANTS",
    "PEPESSANGE",
    "PEPESSOU",
    "PEPESTAFF",
    "PEPESTARBOY",
    "PEPESTONED",
    "PEPESTORM",
    "PEPESTRANGE",
    "PEPESTYLE",
    "PEPESUMMER",
    "PEPESUMO",
    "PEPESUPREME",
    "PEPESURF",
    "PEPESURFING",
    "PEPESURRECT",
    "PEPESUS",
    "PEPESWITCH",
    "PEPESWORD",
    "PEPESYRINGE",
    "PEPETACO",
    "PEPETANGCLAN",
    "PEPETARD",
    "PEPETARO",
    "PEPETE",
    "PEPETERROR",
    "PEPETERSON",
    "PEPETEX",
    "PEPETHAGORAS",
    "PEPETHEFIRST",
    "PEPETHEFROG",
    "PEPETHESOG",
    "PEPETHETROLL",
    "PEPETHREESIX",
    "PEPETHUGLIFE",
    "PEPETHUR",
    "PEPETIA",
    "PEPETIE",
    "PEPETIME",
    "PEPETIN",
    "PEPETINDER",
    "PEPETIP",
    "PEPETITAN",
    "PEPETODAMOON",
    "PEPETONE",
    "PEPETOPKEK",
    "PEPETOWN",
    "PEPETRADER",
    "PEPETRADERS",
    "PEPETRAIN",
    "PEPETRASH",
    "PEPETRATION",
    "PEPETRAZ",
    "PEPETREK",
    "PEPETREZOR",
    "PEPETRODOL",
    "PEPETRON",
    "PEPETSAMURAI",
    "PEPETSHIRT",
    "PEPETTER",
    "PEPETUITY",
    "PEPETUNADE",
    "PEPETUUR",
    "PEPEUN",
    "PEPEUNGYO",
    "PEPEUNIVERSE",
    "PEPEVANEYCK",
    "PEPEVANHALEN",
    "PEPEVIAGRA",
    "PEPEVICH",
    "PEPEVIDEODRO",
    "PEPEVINCI",
    "PEPEVINNY",
    "PEPEVIRAL",
    "PEPEVOLUTION",
    "PEPEVOORHEES",
    "PEPEWANTSYOU",
    "PEPEWAT",
    "PEPEWATCH",
    "PEPEWATTS",
    "PEPEWAVE",
    "PEPEWEST",
    "PEPEWHITE",
    "PEPEWICKED",
    "PEPEWOKE",
    "PEPEWOMAN",
    "PEPEWONKA",
    "PEPEWORLDCUP",
    "PEPEWYATT",
    "PEPEXECUTIVE",
    "PEPEXGALLERY",
    "PEPEXILE",
    "PEPEXIT",
    "PEPEXMASBOY",
    "PEPEYAKUZA",
    "PEPEYE",
    "PEPEYIP",
    "PEPEYOTES",
    "PEPEZ",
    "PEPEZAALBINO",
    "PEPEZCASH",
    "PEPEZENMSTR",
    "PEPEZEUS",
    "PEPEZILLA",
    "PEPEZIO",
    "PEPEZOMBIE",
    "PEPEZONCARD",
    "PEPFICTION",
    "PEPI",
    "PEPITCHY",
    "PEPLACE",
    "PEPLACERESLT",
    "PEPMANIA",
    "PEPMONDRIAN",
    "PEPOCALYPSE",
    "PEPOCKY",
    "PEPOLLO",
    "PEPONG",
    "PEPTARO",
    "PEPUNCONFIRM",
    "PERAPPA",
    "PEROCHI",
    "PHEONIXPEPE",
    "PHILANTHROPE",
    "PHNTOMOFPEPE",
    "PICASSOPEPE",
    "PIGPEPE",
    "PIMENTOLOAF",
    "PINHEADPEPE",
    "PIRATESPEPES",
    "PISFORPEPE",
    "PLATINUMPEPE",
    "PLAYBOYPEPE",
    "PLEGO",
    "PLINKOPEPE",
    "PMOPEPE",
    "POKERPEPE",
    "PONZIPEPE",
    "PORPEPELAMBO",
    "POSTMDRNPEPE",
    "POWERTOPEPE",
    "PPKING",
    "PPLNMDNTNY",
    "PPPGLOBAL",
    "PREPEDATOR",
    "PRINCESSPEPE",
    "PRIVATEPEPE",
    "PROBLEMSOLVE",
    "PROCESSPEPE",
    "PROOFOFPEPE",
    "PROPHECYPEPE",
    "PROUDPEPEWIN",
    "PSEUDOPEPE",
    "PSYCHEPEPE",
    "PSYKEKDELIC",
    "PTSDPEPE",
    "PUMPINGPEPE",
    "PUNCHPEPE",
    "PUREGOLDPEPE",
    "PUREPEPE",
    "PUTINPEPE",
    "PUZZLEPEPE",
    "PWAPWAPWAPWA",
    "PYTHONPEPE",
    "QBITSPEPE",
    "QPEPE",
    "QQPEPE",
    "QUEGUAYPEPE",
    "QUEPASAPEPE",
    "RABBIPEPE",
    "RADIOPEPE",
    "RAGZTOPEPE",
    "RAIJINPEPE",
    "RAINYPEPE",
    "RAIRPEPE",
    "RAMBOPEPE",
    "RANDOMPEPE",
    "RAREAPPLE",
    "RARECHAVEZ",
    "RARECHERRY",
    "RARECOINMEME",
    "RAREDIETIES",
    "RAREIVANKA",
    "RAREKEKUIT",
    "RARELORDKEK",
    "RAREMRROBOT",
    "RAREPEPE",
    "RAREPEPEDAO",
    "RAREPEPEFONZ",
    "RAREPEPEMAG",
    "RAREPEPENEWS",
    "RAREPEPEPRTY",
    "RAREPEPEPUMP",
    "RAREPEPESHOW",
    "RAREPEPESS",
    "RAREPPODCAST",
    "RARESHADILAY",
    "RARESLIMPEPE",
    "RARESPURDO",
    "RARETEMPLATE",
    "RAREWOLFPEPE",
    "REAPERPEPE",
    "REDPUTINPEPE",
    "RELATEPEPE",
    "RELAXPEPE",
    "REPOPEPE",
    "RERERPERP",
    "RESERVPEPES",
    "RESURKEKTION",
    "RETROPEPE",
    "REVOLUCIONAR",
    "REYPEPE",
    "RGBPEPE",
    "RICFLAIRPEPE",
    "RICHPEPE",
    "RICHPEPEPOOR",
    "RICKANDPEPE",
    "RICKYPEPE",
    "RINGITPEPE",
    "RINGOFPEPE",
    "ROBOTPEPE",
    "ROCKINGPEPE",
    "ROLLINGPEPE",
    "RONINKEK",
    "ROOMRAREPEPE",
    "ROTATINGPEPE",
    "RPBANHAMMER",
    "RPCAGENT",
    "RPDF",
    "RPDUMPSTER",
    "RPEPEARMANDO",
    "RPEPEGOJAIL",
    "RPEPEGOLDENR",
    "RPEPELIGHTER",
    "RPEPERAMI",
    "RPJAILEXIT",
    "RPSILLYWALK",
    "RUBBERPEPE",
    "RUBEUSPEPE",
    "RUBIXPEPE",
    "RUNDMP",
    "RUNTHEPEPE",
    "SADMILKPEPE",
    "SAILMOONPEPE",
    "SAKURANIPEPE",
    "SALTANDPEPE",
    "SALTYTADPEPE",
    "SALVADORPEPE",
    "SAMURAIPEPE",
    "SANDORPEPE",
    "SANDWICHPEPE",
    "SANPOPEPE",
    "SANTAPEPE",
    "SARUTOBIPEPE",
    "SATOSHIRARE",
    "SATURDAYPEPE",
    "SAVEPEPE",
    "SCARFACEPEPE",
    "SCHROEPEPE",
    "SCORPEPE",
    "SCREAMPEPE",
    "SEAMANPEPE",
    "SEAPEPE",
    "SEASIDEPEPE",
    "SECRETPEPE",
    "SECURITYPEPE",
    "SEGWITPEPE",
    "SEGWTPEPE",
    "SELFPORTRAIT",
    "SELLOUTPEPE",
    "SENJUPEPE",
    "SENPAIPEPE",
    "SERVALPEPE",
    "SEVENBITPEPE",
    "SEXAYEPEPE",
    "SEXYLADYPEPE",
    "SGTPEPE",
    "SHADEPEPE",
    "SHADILOUNGE",
    "SHEMANPEPE",
    "SHIALEBPEPE",
    "SHININGPEPE",
    "SHITCOINCARD",
    "SHREKPEPE",
    "SHREMPEPE",
    "SICKDEVPEPE",
    "SITHLORDPEPE",
    "SIXTYSIXPEPE",
    "SKIINGPEPE",
    "SLEEPINGPEPE",
    "SLENDERPEPE",
    "SLIMERPEPE",
    "SLVPEPE",
    "SMELLPEPE",
    "SMITHPEPE",
    "SMUGCHIPS",
    "SMUGGLASSES",
    "SMUGPEPE",
    "SNAPCHATPEPE",
    "SNOTPEPE",
    "SNOWDENPEPE",
    "SOCRATESPEPE",
    "SODAPEPENSKI",
    "SOGGYPEPE",
    "SOJOURNPEPE",
    "SOLDATPEPE",
    "SOLODADPEPE",
    "SONICPEPE",
    "SOUNDOFPEPE",
    "SPACEDADDY",
    "SPCPEPEWOJAK",
    "SPEEDPEPE",
    "SPEPECTRE",
    "SPESSMUHPEPE",
    "SPHINXPEPE",
    "SPIDERMNPEPE",
    "SPIRITPEPE",
    "SQUATCHPEPE",
    "STACYPEPE",
    "STAMPOFKEK",
    "STANDINGPEPE",
    "STANPEPEE",
    "STARLORDKEK",
    "STATUEOFPEPE",
    "STEALPEPE",
    "STILLPEPE",
    "STITCHESPEPE",
    "STORYPEPE",
    "STRIPERPEPE",
    "SUCHSHARE",
    "SUPAPEPE",
    "SUPERMANPEPE",
    "SURFINGPEPE",
    "SUSUKINIPEPE",
    "SWAROPEPE",
    "SZECHUANPEPE",
    "TADPOLEPEPE",
    "TAJPEPE",
    "TAKAKO",
    "TAKARAPEPE",
    "TAKOPEPE",
    "TALESPEPE",
    "TEAPEPE",
    "TECHNOPEPE",
    "TEMPURAPEPE",
    "TENPINPUTIN",
    "TERRIBLEPEPE",
    "TESTNETPEPE",
    "TETSUWANPEPE",
    "THEANCAPEPE",
    "THEARCHIPEPE",
    "THEGODPEPE",
    "THEJOYOFPEPE",
    "THEKINGPEPE",
    "THELASTPEPE",
    "THEMONAPEPE",
    "THEPEPE",
    "THEPEPEKISS",
    "THEPEPELIST",
    "THEPEPENATOR",
    "THEPEPEWHALE",
    "THEPEPEZONE",
    "THESKYPEPE",
    "THEVERYPEPE",
    "THINKINGPEPE",
    "THINPEPE",
    "THISISFINE",
    "THISPEPE",
    "THOTHPEPE",
    "THREEDPEPE",
    "THREEPEPES",
    "THREERARE",
    "THUNDERPEPS",
    "TIKIPEPE",
    "TIMEPEPE",
    "TIMETRAVELPP",
    "TITANICPEPE",
    "TLCPEPE",
    "TOBIASPEPE",
    "TODAMOONPEPE",
    "TOMANDPEPE",
    "TOMATOPEPE",
    "TOPCUCK",
    "TOREROPEPE",
    "TOWEROFPEPE",
    "TRAITORPEPE",
    "TRANSMEME",
    "TRANSPOSE",
    "TREEOFPEPE",
    "TRINITYPEPE",
    "TRIPPYPEPE",
    "TROUTPEPE",
    "TRUMPEPE",
    "TRUMPRARE",
    "TRUMPWALL",
    "TSUPEPE",
    "TUBBIES",
    "TUPACPEP",
    "TUXPEPE",
    "TWEEKPEPE",
    "TWNOFEVNGLST",
    "TWOPLYPEPE",
    "UFOPEPE",
    "UKIPEPE",
    "UKIYOEPEPE",
    "ULTIMATEPEPE",
    "ULTRAPEPE",
    "UMENIPEPE",
    "UNCLEPEPE",
    "UNCLEPEPESAM",
    "UNGAISOUTEN",
    "UNITEDPEPE",
    "UNLUCKYPEPE",
    "UPINSMKPEPE",
    "USMCPEPE",
    "UZUMAKIPEPE",
    "VANGOUGHPEPE",
    "VANILLAPEPE",
    "VAPORMAGIC",
    "VAULTBOYPEPE",
    "VEGANPEPE",
    "VEGGIEPEPE",
    "VENUSPEPE",
    "VERIFIEDPEPE",
    "VERYDOGEPEPE",
    "VICEPEPE",
    "VIKINGSPEPE",
    "VINCEMCPEPE",
    "VINTAGEPEP",
    "VIRUSPEPE",
    "VOLDEPEPE",
    "VONPEPEHAYEK",
    "VRPEPE",
    "VSTRSSLBRTCH",
    "WALLPEPE",
    "WAMPUMPEPE",
    "WANKSYPEPE",
    "WANTEDPEPE",
    "WARRIORPEPE",
    "WEAREALLPEPE",
    "WEEDTIME",
    "WESTERNPEPE",
    "WHEELOFPEPE",
    "WHERESPEPE",
    "WHISKEYPEPE",
    "WHOAPEPE",
    "WHOTHATPEPE",
    "WILDPEPE",
    "WILEPEPE",
    "WINKELPEPE",
    "WINSTONPEPE",
    "WIREDPEPE",
    "WISEPEPE",
    "WITCHBLADE",
    "WNPEPEPEPEPE",
    "WOKEPEPE",
    "WOLONGPEPE",
    "WORLDOFPEPE",
    "WPPEPE",
    "WWFPEPE",
    "XCHAINPEPE",
    "XMASANTAPEPE",
    "XMASPEPE",
    "XOBLORTPEPE",
    "XONOTICPEPE",
    "XPEPE",
    "YAMAPEPE",
    "YAMATOPEPE",
    "YANAGINIPEPE",
    "YELLPEPE",
    "YETIPEPE",
    "YOGAPEPE",
    "YOUCANPEPE",
    "YUGUREPEPE",
    "YUMMYPEPE",
    "ZENAFPEPE",
    "ZEROWINGPEPE",
    "ZETAPEPE",
    "ZIKAPEPE",
    "ZOETROPEPE",
    "ZOMBIEPEPES",
    "ZOOKOPEPE",
    "ZZTOPEPE",
    "ZZZZPEPE",
    "BABERUTHPEPE",
    "BADWISHES",
    "BARBARIANPEP",
    "BATMANNPEPE",
    "BCCPEPE",
    "BEAUTYPEPE",
    "BODYBACKPEPE",
    "BOOGERPEPE",
    "BREITBARTPEP",
    "BULBEGAR",
    "BULLSEYEPEPE",
    "CACTUSPEPE",
    "CALMHODLPEPE",
    "CAMPINGPEPE",
    "CAPEPELE",
    "CARLOSPEPE",
    "CERSEIPEPE",
    "CHECKPEPE",
    "CHERRYONTOP",
    "CHUWAPEPE",
    "CLUBSPEPE",
    "COBAINPEPE",
    "COINEATER",
    "CONSPIRATARD",
    "CRIMINALPEPE",
    "CRYPTOPEPES",
    "CYBERPEP",
    "DAWNOTHEPEPE",
    "DELUXEPEPEHD",
    "DIAMONDSPEPE",
    "EATEPEPE",
    "ECLIPTICPEPE",
    "EGGPLANTMKNY",
    "FAIRYCASH",
    "FASHIONPEP",
    "FFFFFFFFFFFF",
    "FLAMINPEPE",
    "FORKPEPE",
    "GAMABUNTA",
    "GAMBITPEPE",
    "GENPEPE",
    "GERPER",
    "GIANCARLO",
    "GROYAPEPE",
    "GROYLEX",
    "GROYONOMICON",
    "GROYPAUCTION",
    "GROYPERDB",
    "GROYPERMONKY",
    "GROYPERTL",
    "GROYPMAN",
    "GUNSNPEPES",
    "HARAKIRIPEPE",
    "HEARTSPEPE",
    "HINAMATSURI",
    "HODLERPEPE",
    "HODLPEPECASH",
    "HOODEDPEPE",
    "HORRORCOIN",
    "HUCKAPEPE",
    "ILUMINATRARE",
    "INDIANAPEPE",
    "ITPEPE",
    "JANDPEPE",
    "JOLIELEGPEPE",
    "JORDANPEPE",
    "JUDYPEPE",
    "JURASSICKEK",
    "KATPEPA",
    "KEKEVOLUTION",
    "KEKFURY",
    "KEKKETY",
    "KEKMONTECRLO",
    "KEKOGGS",
    "KFPEPE",
    "KINGRINGPEPE",
    "KRUEGERPEPE",
    "KUNAIKEK",
    "KYUDOPEPE",
    "LAUGHINGMAN",
    "LEIAORGAPEPE",
    "LIGHTITON",
    "LILROCKETMAN",
    "LITTLEGREEN",
    "LTCPEPE",
    "MAJESTYPEPE",
    "MARGINED",
    "MATRYOSHKAPP",
    "MCGROYPER",
    "MEGAPEPEMAN",
    "MERMAIDPEPE",
    "MILLIONAIRPP",
    "MMXVIII",
    "MOONPEPESUN",
    "MRTALPHA",
    "MUPEPETS",
    "MURASAKIPEPE",
    "NATTYALPHA",
    "NBAPEPE",
    "NIGHTKINGPEP",
    "NOBUSHIPEPE",
    "OMEGAPEPE",
    "ONEEYEMONKEY",
    "ONSENPEPE",
    "OROCHIPEPE",
    "OUIJAPEPE",
    "PAJAMASPEPE",
    "PAXOLOTL",
    "PEBAY",
    "PEBBLEE",
    "PECATRINA",
    "PECTERIA",
    "PEDURO",
    "PEFUNGUS",
    "PENNYPEPE",
    "PEPAGEISHA",
    "PEPALISA",
    "PEPBOT",
    "PEPCASSO",
    "PEPEACTION",
    "PEPEADDICTS",
    "PEPEAFRIKEK",
    "PEPEAKIBA",
    "PEPEAMANIA",
    "PEPEANGEL",
    "PEPEAVENGER",
    "PEPEBALLOON",
    "PEPEBOSCH",
    "PEPEBUSHIDO",
    "PEPEBUZZ",
    "PEPECAFFE",
    "PEPECAGE",
    "PEPECAKEK",
    "PEPECART",
    "PEPECEZANNE",
    "PEPECLOCK",
    "PEPEDARWIN",
    "PEPEDAUGHTER",
    "PEPEDESIGN",
    "PEPEDICK",
    "PEPEDINHO",
    "PEPEDPOOL",
    "PEPEDRINO",
    "PEPEELITE",
    "PEPEFANTASY",
    "PEPEFARMER",
    "PEPEFLIES",
    "PEPEFURIOUS",
    "PEPEGIANT",
    "PEPEGRAFFITI",
    "PEPEGROYA",
    "PEPEHAWKING",
    "PEPEHONGKONG",
    "PEPEHUNDRED",
    "PEPEIT",
    "PEPEJ",
    "PEPEJACKSON",
    "PEPEJOCKER",
    "PEPEKFC",
    "PEPEKITTIES",
    "PEPEKK",
    "PEPEKUN",
    "PEPELIBRIUM",
    "PEPELOCATION",
    "PEPEMASK",
    "PEPEMERMAN",
    "PEPEMICO",
    "PEPEMIND",
    "PEPEMIRO",
    "PEPEMNEMONIC",
    "PEPEMOJI",
    "PEPEMUACK",
    "PEPENAUT",
    "PEPENDRIX",
    "PEPENEON",
    "PEPENICTESLA",
    "PEPENNATOR",
    "PEPENOK",
    "PEPEOLDONE",
    "PEPEOPOLIS",
    "PEPEPAIDCARD",
    "PEPEPARIETAL",
    "PEPEPEACOCK",
    "PEPEPEEPS",
    "PEPEPOST",
    "PEPEPRAKEK",
    "PEPEPRINT",
    "PEPEQQ",
    "PEPERAREPEPE",
    "PEPERCULESS",
    "PEPERELOADED",
    "PEPEREME",
    "PEPEROCKWELL",
    "PEPEROOTS",
    "PEPESGYM",
    "PEPESINLOVE",
    "PEPESKEK",
    "PEPESTRY",
    "PEPETAR",
    "PEPETAXMAN",
    "PEPETHOR",
    "PEPETOBI",
    "PEPETOULLE",
    "PEPETRO",
    "PEPEUBU",
    "PEPEVYPER",
    "PEPEWAY",
    "PEPEWISHPERS",
    "PEPEXMAS",
    "PICKLEPEPE",
    "PINCHAN",
    "PIRATPEPE",
    "POWH",
    "PRISONERPEPE",
    "PSYCHICPEPE",
    "PUFFPEPE",
    "PYJAMASPEPE",
    "RANGOPEPE",
    "RAOULDUKEPEP",
    "RARECARDDECK",
    "RAREGROYPER",
    "RAREINKONE",
    "RARELEAGUE",
    "RARELEE",
    "RAREPEGO",
    "RAREPEPENOTE",
    "RAREPITUFINA",
    "RAREPOTTER",
    "RAREQUEEM",
    "RAREZOMBIE",
    "REALPEPEOFBH",
    "ROADMAPEPE",
    "ROCKETPEPE",
    "RPEPE",
    "SAKURAPENPEN",
    "SALVATORPEPE",
    "SEDUSAPEP",
    "SHAKAPEPE",
    "SHININGXPEPE",
    "SICKPEPE",
    "SISTNCHAPEPE",
    "SKULLPEPE",
    "SMALLRATPEPE",
    "SNOWMANPEPE",
    "SPACECOOKIE",
    "SPACEMOUTH",
    "SPACEXPEPE",
    "SPADESPEPE",
    "SPOCKPEPE",
    "STONEPEPE",
    "STORMYTRUMP",
    "SUCKMYPEPE",
    "THEKING",
    "THELAWNMOWER",
    "THEMASKRARE",
    "THENEWYORKEK",
    "THEPEPEHOFF",
    "TRAININGT",
    "TSUNADE",
    "TWOWEEKSPEPE",
    "UBUNTUPEPE",
    "UGANDANPEPE",
    "UNDEADPEPE",
    "WAYPEPE",
    "WEREWOLFKEK",
    "WITCHPEPE",
    "WITCHRARE",
    "WORLDPEPEHD",
    "XENOPEPE",
    "XIPEPE",
    "YODAPEP",
    "YODAPEPE",
    "YUNOPEPE",
    "ZAZENPEPE"
]

RAREPEPES.forEach(pepe =>  {
    PRESETS[pepe] = {
        group: "RARE PEPES"
    }
})



PRESETS = {
    ...PRESETS,
    ...{
	"FREEDOMKEK": {
		series: 0,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/img_8604.jpg'
	},
	"YOURBASEPEPE": {
		series: 0,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/yourbasepepe-1.gif'
	},
	"BRRRRRRRRRRR": {
		series : 0,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/pokbppp-1.gif'
	},
	"KARPEPELES": {
		series: 0,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/sfb98qp.jpg'
	},
	"FAKEASF": {
		series: 0,
        group: "FAKE RARES",
		img_url: 'https://digirare.com/storage/fake-rare/FAKEASF.gif'
	},

	"FAKETORCH": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKAMOTO": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"WAGMIPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEGRAM": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"SEETHRUPEPHD": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"LABRADEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPEKAWS": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPELENOIR": {
		series: 1,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/z2jxcji.jpg'
	},
	"NOFAPPEPE.crema": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPEORBIT": {
		series: 1,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/cup5ks3.gif'
	},
	"FAKESCAPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: 'https://fakeraredirectory.files.wordpress.com/2021/10/s5zzvxa.jpg'
	},
	"PEPETHER": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"SEAOFFROG": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PHONEYSIMPSO": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEBEEPLE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"DARKCASHGRAB": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEBALLS": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPETOTER": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},

	"FAKEHAIRPEP": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"HODLPIGPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"OMARPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEDEMISE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPETHEFAKE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"TABLOIDPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPEHODLPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"ROCKPEPESCSR": {
		series: 1,
		img_url: ''
	},
	"VASECTOEPE": {
		series: 1,
		img_url: '',
        group: "FAKE RARES"
	},
	"PEPEANDLILY": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKESCREAM": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"NATTYPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PONZIBEAR": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"LORDKEKPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"LORDFAKA": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPSIPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PARREPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"DUCHAMPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKECALLS": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPTANGCLAN": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEPEPELISA": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"REPEPERATION": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"BLOOMER": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPEDWARDFK": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"POPOPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEINVSPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"RAREPEPEPD": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEHOURY": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"MAKEARTPEPE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"ROEFAKE": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"REPEPERATION": {
		series: 1,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEBANKSY": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKETEARS": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"RIVETERPEPE": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"JSONPEPE": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"PEPEBILLIONS": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"FAKEQUEEN": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"COLLEGEMONEY": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"SAINTPEPE": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},
	"LANDWOLFPEPE": {
		series: 2,
        group: "FAKE RARES",
		img_url: ''
	},

    "FEELSGOODGRL" : {group:"FAKE RARES", series: 2},
    "PEPEMANTLE" : {group:"FAKE RARES", series: 2},
    "FAKEFRIDA" : {group:"FAKE RARES", series: 2},
    "CYBERPEPUNK" : {group:"FAKE RARES", series: 2},
    "PEPEESCOBAR" : {group:"FAKE RARES", series: 2},
    "TYSONFURY" : {group:"FAKE RARES", series: 2},
    "HODLHALPEPE" : {group:"FAKE RARES", series: 2},
    "FAKEDJPEPE" : {group:"FAKE RARES", series: 2},
    "BELLPEPE" : {group:"FAKE RARES", series: 2},
    "PEPANDEMIC" : {group:"FAKE RARES", series: 2},
    "FAKEROCK" : {group:"FAKE RARES", series: 2},
    "PEPEKINDNESS" : {group:"FAKE RARES", series: 2},
    "CHILLPEPEROSS" : {group:"FAKE RARES", series: 2},
    "NOOBGRAM" : {group:"FAKE RARES", series: 2},
    "FAKEPEPA" : {group:"FAKE RARES", series: 2},
    "LADTSUNADE" : {group:"FAKE RARES", series: 2},
    "FAKEWYOMING" : {group:"FAKE RARES", series: 2},
    "RAREPEPA" : {group:"FAKE RARES", series: 2},
    "PEPESTREAM" : {group:"FAKE RARES", series: 2},
    "PEPEINSPACE" : {group:"FAKE RARES", series: 2},
    "DANKGOD" : {group:"FAKE RARES", series: 2},
    "FAKEJEEZY" : {group:"FAKE RARES", series: 2},
    "PEPELALA" : {group:"FAKE RARES", series: 2},
    "PEPESHIFT" : {group:"FAKE RARES", series: 2},
    "LAFAKANOSTRA" : {group:"FAKE RARES", series: 2},
    "SCHIFFPEPE" : {group:"FAKE RARES", series: 2},
    "FAKARIO" : {group:"FAKE RARES", series: 2},
    "FIRSTTWEET" : {group:"FAKE RARES", series: 2},
    "FAIKUPEPE" : {group:"FAKE RARES", series: 2},
    "BLOKLETCHAIN" : {group:"FAKE RARES", series: 2},
    "PEPSTEIN" : {group:"FAKE RARES", series: 2},
    "THEDONPEPE" : {group:"FAKE RARES", series: 2},
    "SQUIGGLEPEPE" : {group:"FAKE RARES", series: 2},
    "FAKELORDKEK" : {group:"FAKE RARES", series: 2},
    "DREAMTEAM" : {group:"FAKE RARES", series: 2},
    "FAKEGAMERP" : {group:"FAKE RARES", series: 2},
    "PEPEDENZA" : {group:"FAKE RARES", series: 2},
    "BASEDGODPEPE" : {group:"FAKE RARES", series: 2},
    "PEPEMUNDI": {group: "FAKE RARES",series: 2, artist: "PEPENARDO"},
    "PEPENIRO" : { group: "FAKE RARES", artist: "Dimzayan", series: 2},
    "PEPEPLEBZ" : { group: "FAKE RARES", artist: "Dimzayan", series: 2},
    "PEPELIOTTA" : { group: "FAKE RARES", artist: "Dimzayan", series: 3},

    "LFNONE": {
        group: "FAKA NOSTRA"
    },

    "LFNTWO": {
        group: "FAKA NOSTRA"
    },
    "LFNTHREE": {
        group: "FAKA NOSTRA"
    },
    "LFNFOUR": {
        group: "FAKA NOSTRA"
    },
    "LAFAKANOSTRA": {
        group: "FAKA NOSTRA"
    },
    "A11107355150182719202" : {
        group: "BULLTARDIA", artist: "Dimzayan"
    },
    "A11118957393733662646" : {
        group : "BULLTARDIA", artist: "Dimzayan"
    },
    "MOONFROGS" : {
        group: "FAKE FAKES", artist: "Dimzayan"
    },
    "GOODBADPEPE" : {
        group: "FAKE FAKES", artist: "Dimzayan"
    },

    
    "FAKEFRIDA": {
        group: "FAKE RARES"
    },
    "DANKGOD": {
        group: "FAKE RARES"
    },
    "PEPEDANZA": {
        group: "FAKE RARES"
    },
    "PEPEMANTLE": {
        group: "FAKE RARES"
    },
    "PEPEKINDNESS": {
        group: "FAKE RARES"
    }
}}

