name = "dim-api"
main = "index.js"
compatibility_date = "2024-09-23"

# After `wrangler kv:namespace create DIM_KV`, replace the id below with the real one.
[[kv_namespaces]]
binding = "DIM_KV"
id = "f413e3b7359e490690039d30e94a78ce"

[[routes]]
pattern = "dimzayan.com/api/*"
zone_id = "8eeb7820ef96796038b1c4d7278aa1f8"
